spring.application.name=antech

server.port=8080

# MySQL8 설정
spring.datasource.url=jdbc:mysql://project-db-cgi.smhrd.com:3307/cgi_24K_bigdata26_p3_3?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=cgi_24K_bigdata26_p3_3
spring.datasource.password=smhrd3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 실행되는 SQL 쿼리 출력
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Spring Boot에서 ANSI 컬러 활성화
spring.output.ansi.enabled=ALWAYS

# MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml

# MyBatis Type Alias 설정 (Model 패키지 경로)
mybatis.type-aliases-package=com.ans.antech.model

# Spring Mail 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rhdudqls652@gmail.com
spring.mail.password=cxpwfwzeawjhroqe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.debug=true

# 파일 업로드를 위한 환경설정 추가
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

